### ISSUE TITLE
"Door Open, Start Session" is a standby state where the system is blind

### ISSUE THREAD

**Issue by sampathsatti** [bravetechnologycoop/ODetect-Backend-Local#1]
"Door Open, Start Session" is a session state that is triggered by the door opening when the system is in the "no presence, no session state".

1. The nomenclature is a slight misnomer, as the session doesn't actually start.

2. Rather the system is an standby state, where it waits for the door to close. 

3. Additionally, the system is blind to any behavior in the bathroom

**Comment by sampathsatti** [comment]
"Door Open Start Sessions" must start a session when motion is active and move into the motion state

**Comment by mariocimet** [comment]
assigning @trisapeace to make a failing test for this

**Comment by trisapeace** [comment]
@sampathsatti I started a branch called "fix_door_open_blindness" where I added test that should cover the movement transition between DOOR_OPEN_START and MOVEMENT_DETECTED. 

It works under the assumption that the criteria for movement is the same as the transition from NO_PRESENCE_NO_SESSION to MOVEMENT_DETECTED.

Please use this branch for further changes for this Issue. Then you'll be able to run `npm test` to see the tests pass :-) Thanks!

**Comment by mariocimet** [comment]
As mentioned in the pull request, there's some tests passing for this, but I wonder if we've specified the problem correctly. I think that what would happen now is that the system would be *less blind* but still possibly blind if movement_fast is under the threshold (even if the SmartThings Motion Sensor is activated).

**Comment by mariocimet** [comment]
This needs a wholesale bottom-up system change: we're planning on redoing the state machine anyways and this would be an outcome of that.
