### ISSUE TITLE
Create Xethru Heartbeat

### ISSUE THREAD

**Issue by mariocimet** [bravetechnologycoop/ODetect-Backend-Local#12]
If the last time stamp for the XeThru is more than ten seconds ago, trigger an SMS message to Mario + Sampath.

**Comment by mariocimet** [comment]
@sampathsatti current plan is to use timestamp generated when a row is inserted into the database (i.e. when im about to insert the new xethru data, I check if the last published_at is >10 seconds ago.

Alternately (and this would take more work), we could send a timestamp from the particle itself. Any thoughts?

**Comment by sampathsatti** [comment]
Not sure if the timestamp from the particle will differ from the server. I'm more inclined to go with the timestamp from the latter (the server). I think using the last automatically generated timestamp in the XeThru database would be best way to go

So this logic would go into the handler for the POST request?
