### ISSUE TITLE
Transition from Door Closed Start to Movement is too permissive

### ISSUE THREAD

**Issue by trisapeace** [bravetechnologycoop/ODetect-Backend-Local#3]
In `sessionState.js`, the code for the transition from Door Closed Start to Movement is 
```
                case STATE.DOOR_CLOSED_START:
                    {
                        if (xethru.state != XETHRU_STATE.NO_MOVEMENT || motion.signal == "active") {
                            state = STATE.MOVEMENT;
                        }
                        break;
                    }
```

But that means that the transition happens when the XeThru has states such as `UNKNOWN`, `INITIALIZING`, and `ERROR` and also when the XeThru has no state at all. (Will the XeThru ever not have a state in the DB?). I feel like this is too permissive and that XeThru states that would cause this transition to happen would be only `MOVEMENT`, `BREATHING`, and maybe `MOVEMENT_TRACKING`.

**Comment by mariocimet** [comment]
Yay! @trisapeace puts this one down with #14
