### ISSUE TITLE
Investigate whether MOTION_DETECTED, MOVEMENT, BREATHING, and STILL can be merged into a single state

### ISSUE THREAD

**Issue by trisapeace** [bravetechnologycoop/ODetect-Backend-Local#5]
`MOVEMENT_DETECTED` automatically transitions to `MOVEMENT` on the next round of the state machine no matter what the conditions. If there is nothing else relying on knowing the difference between the two, I suggest that they be just a single state.

`MOVEMENT`, `BREATHING`, and `STILL` all appear to have the same behaviour with regards to the rest of the system. They all transition to `DOOR_OPEN_CLOSE` with the same conditions. They all transition to `OD_SUSPECTED` with the same conditions. And they all transition `NO_PRESENCE_CLOSE` with the same conditions. If there is nothing else relying on knowing the difference between these three states, I suggest that they are just a single state.

Maybe we can call this state `MONITORING` or something like that?

**Comment by mariocimet** [comment]
Closing this issue because we need a in-between state here to start a session, and session starting happens outside the State Machine in index.js
