### ISSUE TITLE
Transition from MOVEMENT/STILL/BREATHING to SUSPECTED_OD is too restrictive

### ISSUE THREAD

**Issue by trisapeace** [bravetechnologycoop/ODetect-Backend-Local#6]
The condition logic that says when to go from `MOVEMENT`/`STILL`/`BREATHING` to `SUSPECTED_OD` checks two values:
```
                        if (session.od_flag == OD_FLAG_STATE.NO_OVERDOSE && await db.isOverdoseSuspected(xethru, session, location_data)) {
                            state = STATE.SUSPECTED_OD;
                        }
```
Which I believe is saying "if we didn't expect an overdose before, but now we do, transition to `SUSPECTED_OD`". But what if we ended up in a weird state where we already *did* suspect an overdose. With the current logic that means that we would *not* transition to SUSPECTED_OD. I feel like we would want to transition whenever the `db.isOverdoseSuspected` function comes back true regardless of what we knew about it before. What do you think?

**Comment by trisapeace** [comment]
I see that the `SUSPECTED_OD` state immediately transitions back to `STILL` in the code, hence the need to distinguish whether the chatbot has already been enabled for this session or not. This transition is, understandably, not in the diagram in the Google Doc. 

In some ways, what this has done is created a doubles of the MOVEMENT, STILL, and BREATHING states. You have a MOVEMENT_WITHOUT_SUSPECTED_OD and MOVEMENT_WITH_SUSPECTED_OD and you have STILL_WITHOUT_SUSPECTED_OD and STILL_WITH_SUSPECTED_OD and you have BREATHING_WITHOUT_SUSPECTED_OD and BREATHING_WITH_SUSPECTED_OD.

When really what you want instead of going back to STILL (which is really STILL_WITH_SUSPECTED_OD), it should just chill in the SUSPECTED_OD state until one of the conditions is met to transition it out in one of the three ways that it could move out (chatbot completes, door closes, or no presence is detected).

I've left a diagram at Mario's desk showing what I'm thinking at this point. Let me know if I can clarify any of that.

**Comment by gordonwcasey** [comment]
Am loving all of this and... I believe that if we get as far as the <SUSPECTED_OD> state, we should insist that a human (i.e. the chatbot) permits a transition to another state. 

No?
